bangazonworkforcemgt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from hrapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrapp.urls'))
]

hrapp/urls.py
from django.urls import path, reverse
from django.conf.urls import include
from hrapp import views
from .views import *

app_name = 'hrapp'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('computers/', computer_list, name='computers'),
    path('computers/form', computer_form, name='computer_form'),
    path('computers/<int:computer_id>/', computer_details, name='computer_details'),
    path('computers/delete/<int:computer_id>', computer_delete, name='computer_delete'),
    path('employees/', employee_list, name='employee_list'),
    path('employees/<int:employee_id>/', employee_details, name='employee'),
    path('employees/form', employee_form, name='employee_form'),
    path('employees/<int:employee_id>/form/', employee_edit_form, name='employee_edit_form'),
    path('employees/<int:employee_id>/assigntraining', training_program_assign_employee, name='employee_assign_training'),

    path('trainings/', training_list, name='training_list'),
    path('trainings/form', training_form, name='training_form'),
    path('trainings/past', past_training_list, name='past_training_list'),
    path('trainings/<int:training_id>', training_details, name='training'),
    path('trainings/<int:training_id>/form/', training_edit_form, name='training_edit_form'),
    path('departments/', department_list, name='department_list'),
    path('departments/<int:department_id>', department_details, name='department'),
    path('departments/form', department_form, name='department_form'),
]

hrapp/models/computer.py
from django.db import models

class Computer(models.Model):
    '''
    description: This class creates a computer and its properties
    author: Joe Shep
    properties:
      make: The make will contain the name of the brand of the computer.
      purchase_date: This property contains the purchase date in string form.
      decomission_date: This property contains the dicomission date in string form.
      employees: This property contains the many to many relationship with the computer/employee model
    '''

    make = models.CharField(max_length=20)
    purchase_date = models.DateField()
    decommission_date = models.DateField(null=True, blank=True, default=None)
    employees = models.ManyToManyField("Employee", through='EmployeeComputer')

    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def __str__(self):
        return f"{self.make}"

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

hrapp/models/department.py
from django.db import models

class Department(models.Model):
    name = models.CharField(max_length=25)
    budget = models.IntegerField()

    def __str__(self):
        return f"{self.name}"
    

hrapp/models/employee.py
from django.db import models


class Employee(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    start_date = models.DateField()
    is_supervisor = models.BooleanField(default=False)
    department = models.ForeignKey("Department", on_delete=models.CASCADE)
    training_programs = models.ManyToManyField("TrainingProgram", through='TrainingProgramEmployee')

    class Meta:
        verbose_name = ("Employee")
        verbose_name_plural = ("Employees")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("Employee_detail", kwargs={"pk": self.pk})

hrapp/models/employee_computer.py
from django.db import models

class EmployeeComputer(models.Model):
    """
    Creates the join table for the many to many relationship between computers and employees
    Author: Joe Shep
    methods: none
    """

    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    computer = models.ForeignKey("Computer", on_delete=models.CASCADE)
    assigned_date = models.DateField()
    unassigned_date = models.DateField(null=True, blank=True, default=None)

hrapp/models/model_factory.py
import sqlite3


# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

hrapp/models/training_program.py
from django.db import models

class TrainingProgram(models.Model):
    title = models.CharField(max_length=25)
    description = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    capacity = models.IntegerField()

hrapp/models/training_program_employee.py
from django.db import models

class TrainingProgramEmployee(models.Model):
    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    training_program = models.ForeignKey("TrainingProgram", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("TrainingProgramEmployee")
        verbose_name_plural = ("TrainingProgramEmployees")

hrapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {
            "request": request
        }

        return render(request, template, context)

hrapp/templates/computers/delete.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="computer-delete">
    <h2>Are you sure you want to delete this computer?</h2>
</section>
    <form action="{% url 'hrapp:computer_details' computer_id %}" method="POST">
    {% csrf_token %}
      <input type="hidden" name="actual_method" value="DELETE">
      <button>Delete</button>
    </form> 
    <form action="{% url 'hrapp:computer_details' computer_id %}" method="GET">
    {% csrf_token %}
      <button>Nevermind</button>
    </form> 
    
  </body>
{% endblock %}

hrapp/templates/computers/details.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="computer-details">
    <h1>{{ computer.make }}</h1>
    <h2>Purchase Date: {{ computer.purchase_date }}</h2>

    <div>Decommissioned: {{ computer.decommission_date }}</div>
    <div>Current User: {{ computer.current_user}} </div>
</section>
    {% if computer.current_user == "Unassigned" %}
    <form action="{% url 'hrapp:computer_delete' computer.id %}" method="GET">
    {% csrf_token %}
      <button>Delete</button>
    </form> 
    {% else%}
    <div> A computer cannot be deleted once it is assigned. </div>
    {% endif %}

    
    
  </body>
{% endblock %}

hrapp/templates/computers/form.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Register New Computer</h1>


    <form action="{% url 'hrapp:computers' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="make">Make: </label>
          <input id="make" type="text" name="make">
      </fieldset>
      <fieldset>
      <label for='employee'>Assign to an Employee</label>
      <select id="employee" type="text" name="employee" >
                <option value='0' > Leave Unassigned</option>
                {% for person in employees %}
                    <option value="{{ person.id }}"> {{ person.first_name }} {{person.last_name}} </option>
                {% endfor %}
          </select>
      </fieldset>
      

      <input type="submit" value="Add It" />
    </form>
  {% endblock %}

hrapp/templates/computers/list.html
{% extends 'shared/base.html' %}

{% block content %}
<article class="pa1 pa1-ns">
<h1 class="f4 bold center mw6">Computers</h1>
<ol class="list pl0 ml0 center mw6 ba b--light-silver br2">
{% for computer in computers %}
    

    <li class="ph3 pv3 bb b--light-silver">
        <a href="{% url 'hrapp:computer_details' computer.id %}">
                {{ computer.make }}
            </a>
        {% comment %} <div> Purchase Date: {{computer.purchase_date}}
        Decommission Date: {{computer.decommission_date}} </div>
        <div> Current User: {{computer.current_user}} </div> {% endcomment %}
    </li>
{% endfor %}
</ol>
</article>
<div class="flex items-center justify-center ">
<form action="{% url 'hrapp:computer_form' %}"><button class="f5 no-underline black bg-animate hover-bg-black hover-white inline-flex items-center pa3 ba border-box mr4">Register New Computer</button></form>
</div>
{% endblock content %}

hrapp/templates/computers/list_view_only.html
{% extends 'shared/base.html' %}

{% block content %}
<article class="pa1 pa1-ns">
<h1 class="f4 bold tc center mw6">Computers</h1>
<ol class="list pl0 ml0 center mw6 ba b--light-silver br2">
{% for computer in computers %}
    

    <li class="ph3 pv3 bb b--light-silver">
        <h4>
                {{ computer.make }}
            </h4>
        {% comment %} <div> Purchase Date: {{computer.purchase_date}}
        Decommission Date: {{computer.decommission_date}} </div>
        <div> Current User: {{computer.current_user}} </div> {% endcomment %}
    </li>
{% endfor %}
</ol>
</article>
{% endblock content %}

hrapp/templates/departments/department_detail.html
{% extends 'shared/base.html'%}

{% block content %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Department</title>
  </head>
  <body>
    <h1>{{ department.name }}</h1>
    <h2>Has a budget of: {{ department.budget }}</h2>
    <div>Employees in the department:</div>
    <ul>
    {% for employee in employees %}
    <li>{{ employee.first_name }} {{ employee.last_name }}</li>
    {% endfor %}
    </ul>
  </body>
</html>
{% endblock %}

hrapp/templates/departments/department_form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Create Department</h1>


    <form action="{% url 'hrapp:department_list' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="name">Name: </label>
          <input id="name" type="text" name="name">
      </fieldset>
      <fieldset>
          <label for="budget">Budget: </label>
          <input id="budget" type="text" name="budget">
      </fieldset>

      <input type="submit" value="Submit" />
    </form>
  </body>
</html>

hrapp/templates/departments/department_list.html
{% extends 'shared/base.html' %}

{% block content %}
<article class="pa1 pa1-ns">
<h1 class="f4 bold tc center mw6">Departments</h1>

<ol class="list pl0 ml0 center mw6 ba b--light-silver br2">
{% for department in departments %}
    <li class="ph3 pv3 bb b--light-silver">
        
        <a href="{% url 'hrapp:department' department.id %}"> {{ department.name }} </a>
        <br>
        Budget: {{ department.budget }}
        <br>
        Number of Employees: {{ department.size }}

        {% comment %} <p>{{ department.name }}</p>
        Budget: {{ department.budget }} {% endcomment %}

    </li>
{% endfor %}
</ol>
</article>
<div class="flex items-center justify-center">
<form action="{% url 'hrapp:department_form' %}"><button class="f5 no-underline black bg-animate hover-bg-black hover-white inline-flex items-center pa3 ba border-box mr4">Create Department</button></form>
</div>
{% endblock content %}

hrapp/templates/departments/department_list_view_only.html
{% extends 'shared/base.html' %}

{% block content %}
<article class="pa1 pa1-ns">
<h1 class="f4 bold tc center mw6">Departments</h1>

<ol class="list pl0 ml0 center mw6 ba b--light-silver br2">
{% for department in departments %}
    <li class="ph3 pv3 bb b--light-silver">
        
        <h4> {{ department.name }} </h4>
        Budget: {{ department.budget }}

        {% comment %} <p>{{ department.name }}</p>
        Budget: {{ department.budget }} {% endcomment %}
    </li>
{% endfor %}
</ol>
</article>
{% endblock content %}

hrapp/templates/employees/employee_assign_training.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Assign Training</h1>


    <form action="{% url 'hrapp:employee_assign_training' employee_id %}" method="post">
      {% csrf_token %}
      
      <fieldset>
      <label for='training'>Assign to an Training</label>
      <select id="training" type="text" name="training" >
                {% for training in trainings %}
                    <option value="{{ training.id }}"> {{ training.title }}: {{training.start_date}} to {{training.end_date}} </option>
                {% endfor %}
          </select>
      </fieldset>
      {% comment %} <input type="hidden" value={{employee_id}} name='employee_id'/> {% endcomment %}
      <input type="submit" value="Sign Up" />
    </form>
  {% endblock %}

hrapp/templates/employees/employee_detail.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="employee-details">
        <h1>{{ employee }}</h1>
        <ul>
	        <li>Department: {{ employee.department }}</li>
	        <li>Computer: {{ employee.computer }}</li>
	        <li>Training Programs:
	        	<ul>
	            {% for training_program in training_programs %}
	                <li>{{ training_program.title }}</li>
	            {% endfor %}
	           </ul>
	        </li>
      	</ul>
		  <form action="{% url 'hrapp:employee_assign_training' employee.id %}"><button>Assign Training</button></form>
    </section>

    <section id="employee-actions" style="display:flex;">
        <form action="{% url 'hrapp:employee_edit_form' employee.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>
{% endblock %}

hrapp/templates/employees/employees_form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    {% if employee.id is not None %}
        <h1>Edit Employee Information</h1>
    {% else %}
        <h1>Employee Hiring</h1>
    {% endif %} 

    {% if employee.id is not None %}
        <form action="{% url 'hrapp:employee' employee.id %}" method="post">
    {% else %}
        <form action="{% url 'hrapp:employee_list' %}" method="post">
    {% endif %}
      {% csrf_token %}
      <fieldset>
          {% if employee.id is not None %}
                <p>First Name: {{ employee.first_name }}</p>
              {% else %}
                <label for="first_name">First Name: </label>
                <input id="first_name" type="text" name="first_name" value="{{ employee.first_name }}">
          {% endif %}
      </fieldset>
      <fieldset>
          <label for="last_name">Last Name: </label>
          <input id="last_name" type="text" name="last_name" value="{{ employee.last_name }}">
      </fieldset>
      {% if employee.id is None %}
        <fieldset>
            <label for="start_date">Employment Start Date: </label>
            <input id="start_date" type="date" name="start_date">
        </fieldset>
        <fieldset>
            <label for="is_supervisor">Supervisor: </label>
            <select id='is_supervisor' name='is_supervisor'>
            <option value=True >Yes</option>
            <option value=False >No</option>
            </select>  
        </fieldset>
      {% endif %}
      <fieldset>
          <label for="department">Department: </label>
          <select id="department" type="text" name="department">
                {% for department in all_departments %}
                    <option value="{{ department.id }}">{{ department }}</option>
                {% endfor %}
          </select>
      </fieldset>
      {% if employee.id is not None %}
        <fieldset>
            <label for="computer">Computer: </label>
            <select id="computer" type="text" name="computer">
                  {% for computer in all_computers %}
                      <option value="{{ computer.id }}">{{ computer }}</option>
                  {% endfor %}
            </select>
        </fieldset>
      {% endif %}
      {% if employee.id is not None %}
          <input type="hidden" name="actual_method" value="PUT">
          <input type="submit" value="Update" />
      {% else %}
          <input type="submit" value="Create" />
      {% endif %}
    </form>
  </body>
</html>

hrapp/templates/employees/employees_list.html
{% extends 'shared/base.html' %}

{% block content %}
<article class="pa1 pa1-ns">
<h1 class="f4 bold tc center mw6">Employees</h1>

<ol class="list pl0 ml0 center mw6 ba b--light-silver br2">
{% for employee in employees %}
    <li class="ph3 pv3 bb b--light-silver">
        <p><a href="{% url 'hrapp:employee' employee.id %}">{{ employee }}</a></p>
        <p>Department: {{ employee.department }}</p>
    </li>
{% endfor %}
</ol>
 </article>
<div class="flex items-center justify-center">
<form action="{% url 'hrapp:employee_form' %}"><button class="f5 no-underline black bg-animate hover-bg-black hover-white inline-flex items-center pa3 ba border-box mr4">Add Employee</button></form>
</div>
{% endblock content %}

hrapp/templates/employees/employees_list_read_only.html
{% extends 'shared/base.html' %}

{% block content %}
<article class="pa1 pa1-ns">
<h1 class="f4 bold tc center mw6">Employees</h1>

<ol class="list pl0 ml0 center mw6 ba b--light-silver br2">
{% for employee in employees %}
    <li class="ph3 pv3 bb b--light-silver">
        <p><h4>{{ employee }}</h4></p>
        <p>Department: {{ employee.department }}</p>
    </li>
{% endfor %}
</ol>
</article>
{% endblock content %}

hrapp/templates/home.html
{% extends 'shared/base.html' %}

{% block content %}
<h1 class="tc">Welcome to the Bangazon Workforce Management System</h1>
{% endblock content %}

hrapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Bangazon Workforce Management</title>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
    {% block css %}
    {% endblock %}
</head>
<body>
<header class="bg-white black-80 tc pv4 avenir">
  <h1 class="mt2 mb0 baskerville i fw1 f1">Bangazon Workforce Management</h1>
  {% comment %} <h2 class="mt2 mb0 f6 fw4 ttu tracked">Lords of Might and Magic</h2> {% endcomment %}
    <nav id="site-nav" class="bt bb tc mw10 center mt4">
        {% comment %} <ol class="navList"> {% endcomment %}
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:home' %}">Home</a>
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:employee_list' %}">Employees</a>
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:department_list' %}">Departments</a>
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:computers' %}">Computers</a>
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:training_list' %}">Training Programs</a>
            {% if request.user.is_authenticated %}
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:logout' %}">Logout</a>
            {% else %}
            <a class="navList__route f6 f5-l link bg-animate black-80 hover-bg-lightest-blue dib pa3 ph4-l" href="{% url 'hrapp:login' %}">Login</a>
            {% endif %}
        {% comment %} </ol> {% endcomment %}
    </nav>
</header>
    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

hrapp/templates/training_programs/past_training_details.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="training-details">
        <h1>{{ training.title }}</h1>
        <ul>
	        <li>Description: {{ training.description }}</li>
	        <li>Start Date {{ training.start_date }}</li>
	        <li>End Date {{ training.end_date }}</li>
            <li>Max Attendance {{ training.capacity }}</li>
            <li>
                <span>Program Attendees</span>
                <ul>
                    {% for attendee in attendees %}
                        <li>{{ attendee.first_name }} {{ attendee.last_name }}</li>
                    {% endfor %}
                </ul>
            </li>
      	</ul>
    </section>
    <section id="training-actions" style="display:flex;">
        <form action="{% url 'hrapp:training' training.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>
        <form action="{% url 'hrapp:training_edit_form' training.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>


{% endblock %}

hrapp/templates/training_programs/past_training_list.html
{% extends 'shared/base.html' %}

{% block content %}

    <article class="pa1 pa1-ns">
    <h1 class="f4 bold tc center mw6">Past Training Programs</h1>

    <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
    {% for training in trainings %}
        <li class="ph3 pv3 bb b--light-silver">
            <a href="{% url 'hrapp:training' training.id %}">{{ training.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}

hrapp/templates/training_programs/training_details.html
{% extends 'shared/base.html' %}

{% block content %}
    <section id="training-details">
        <h1>{{ training.title }}</h1>
        <ul>
	        <li>Description: {{ training.description }}</li>
	        <li>Start Date {{ training.start_date }}</li>
	        <li>End Date {{ training.end_date }}</li>
	        <li>Max Attendance {{ training.capacity }}</li>
      	</ul>
    </section>
    <section id="training-actions" style="display:flex;">
        <form action="{% url 'hrapp:training' training.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>
        <form action="{% url 'hrapp:training_edit_form' training.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>


{% endblock %}

hrapp/templates/training_programs/training_form.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Training Program Form</h1>

{% if training.id is not None %}
    <form action="{% url 'hrapp:training' training.id %}" method="post">
{% else %}
    <form action="{% url 'hrapp:training_list' %}" method="post">
{% endif %}
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title" value="{{training.title}}">
      </fieldset>
      <fieldset>
          <label for="description">Description: </label>
          <input id="description" type="text" name="description" value="{{training.description}}">
      </fieldset>
      <fieldset>
          <label for="start_date">Start Date: </label>
          <input id="start_date" type="date" name="start_date" value="{{training.start_date}}">
      </fieldset>
      <fieldset>
          <label for="end_date">End Date: </label>
          <input id="end_date" type="date" name="end_date" value="{{training.end_date}}">
      </fieldset>
      <fieldset>
          <label for="capacity">Maximum Attendees: </label>
          <input id="capacity" type="text" name="capacity" value="{{training.capacity}}">
      </fieldset>


        {% if training.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}
    </form>
{% endblock content %}

hrapp/templates/training_programs/training_list.html
{% extends 'shared/base.html' %}

{% block content %}

    <article class="pa1 pa1-ns">
    <h1 class="f4 bold tc center mw6">Training Programs</h1>

    <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
    {% for training in trainings %}
        <li class="ph3 pv3 bb b--light-silver">
            <a href="{% url 'hrapp:training' training.id %}">{{ training.title }}</a>
        </li>
    {% endfor %}
    </ul>
    </article>
    <div class="flex items-center justify-center">
    <form action="{% url 'hrapp:training_form' %}"><button class="f5 no-underline black bg-animate hover-bg-black hover-white inline-flex items-center pa3 ba border-box mr4">Add Training Program</button></form>
    <a class="no-underline" href="{% url 'hrapp:past_training_list' %}"><button class="f5 no-underline black bg-animate hover-bg-black hover-white inline-flex items-center pa3 ba border-box">View Past Training Programs</button></a>
    </div>
{% endblock content %}

hrapp/templates/training_programs/training_list_view_only.html
{% extends 'shared/base.html' %}

{% block content %}

    <article class="pa1 pa1-ns">
    <h1 class="f4 bold tc center mw6">Training Programs</h1>

    <ul class="list pl0 ml0 center mw6 ba b--light-silver br2">
    {% for training in trainings %}
        <li class="ph3 pv3 bb b--light-silver">
            {{ training.title }}
        </li>
    {% endfor %}
    </ul>
    </article>

{% endblock content %}